# Generated by Django 5.0.1 on 2024-01-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='entranceexam',
            name='exam_date',
        ),
    ]
