# Generated by Django 5.0.1 on 2024-01-29 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='eligibility_exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.entranceexam'),
        ),
        migrations.AddField(
            model_name='entranceexam',
            name='full_mark',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='ExamCourseAssociation',
        ),
    ]
