# Generated by Django 5.0.1 on 2024-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_course_eligibility_exam_entranceexam_full_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceexam',
            name='pass_mark',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
