# Generated by Django 5.0.1 on 2024-01-31 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_entranceexam_pass_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='eligibility_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.entranceexam'),
        ),
        migrations.AddField(
            model_name='course',
            name='offering_college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.college'),
        ),
    ]
