# Generated by Django 5.0.1 on 2024-01-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_college_alter_course_eligibility_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='offering_college',
        ),
        migrations.AddField(
            model_name='course',
            name='offering_college',
            field=models.ManyToManyField(null=True, to='exams.college'),
        ),
    ]
