# Generated by Django 5.0.1 on 2024-01-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_course_offering_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='offering_college',
            field=models.ManyToManyField(to='exams.college'),
        ),
    ]
