# Generated by Django 5.0.1 on 2024-01-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_course_offering_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceexam',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
