# Generated by Django 5.0.1 on 2024-02-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_entranceexam_description_entranceexam_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceexam',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entranceexam',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='entranceexam',
            name='university',
            field=models.CharField(max_length=200),
        ),
    ]
