# Generated by Django 5.0.1 on 2024-02-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_entranceexam_description_entranceexam_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='offering_college',
            new_name='offering_colleges',
        ),
        migrations.RemoveField(
            model_name='entranceexam',
            name='level',
        ),
        migrations.AddField(
            model_name='entranceexam',
            name='eligibility_level',
            field=models.CharField(choices=[('Diploma', 'Diploma Level'), ('Bachelors', "Bachelor's Level"), ('Masters', "Master's Level")], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entranceexam',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entranceexam',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='entranceexam',
            name='university',
            field=models.CharField(max_length=200),
        ),
    ]
